"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-h*_+vup+$&%+lf_220*vnojiyzg3ih#aiki)2slb)_3yy19c73"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    "unfold",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # DRF
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    # Local
    "apps.core",
    "apps.authentication",
    "apps.products",
    "apps.cart",
    "apps.payments",
]

# Middleware
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# Authentication and REST
AUTHENTICATION_BACKENDS = {"apps.authentication.backends.EmailAuthenticationBackend"}

AUTH_USER_MODEL = "authentication.user"

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication"
    ],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.IsAuthenticated"],
}

from datetime import timedelta

SIMPLE_JWT = {
    # Life time
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKEN": False,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": False,
    # User config
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
}

# Swagger
SPECTACULAR_SETTINGS = {
    "TITLE": "ECommerce internal API",
    "DESCRIPTION": "Internal API for proceeding ECommerce actions",
    "VERSION": "1.0",
}

# Config
ROOT_URLCONF = "config.urls"

# Templates
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Server
WSGI_APPLICATION = "config.wsgi.application"


# Database
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files
STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

from django.urls import reverse_lazy
UNFOLD = {
    "SITE_TITLE": "My ECommerce",
    "SITE_HEADER": "My ECommerce",
    "SITE_SYMBOL": "Money",
    "SIDEBAR": {
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Authentication",
                "collapsible": False,
                "items": [
                    {
                        "title": "Groups",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    },
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:authentication_user_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    }
                ]
            },
            {
                "title": "Management",
                "collapsible": False,
                "items": [
                    {
                        "title": "Products",
                        "icon": "box",
                        "link": reverse_lazy("admin:products_product_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    },
                    {
                        "title": "Carts",
                        "icon": "shopping_cart",
                        "link": reverse_lazy("admin:cart_cart_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    }
                ]
            },
            {
                "title": "billing",
                "collapsible": False,
                "items": [
                    {
                        "title": "Orders",
                        "icon": "order_approve",
                        "link": reverse_lazy("admin:payments_order_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    },
                    {
                        "title": "Transaction",
                        "icon": "contract",
                        "link": reverse_lazy("admin:payments_transaction_changelist"),
                        "permission": lambda request: request.user.is_superuser
                    }
                ]
            }
        ]
    },
    "TABS": [
        {
            "page": "Products",
            "models": ["products.product"],
            "items": [
                {
                    "title": "All",
                    "link":reverse_lazy("admin:products_product_changelist"),
                    "permission": lambda request: request.user.is_superuser
                },
                {
                    "title": "In stock",
                    "link": lambda request: f"{reverse_lazy("admin:products_product_changelist")}?in_stock__exact=True",
                    "permission": lambda request: request.user.is_superuser
                },
                {
                    "title": "Missing",
                    "link": lambda request: f"{reverse_lazy("admin:products_product_changelist")}?in_stock__exact=False",
                    "permission": lambda request: request.user.is_superuser
                }
            ]
        }
    ]
}